# Generated by Django 4.2.5 on 2023-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='blog/image', verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('url', models.URLField(blank=True, verbose_name='Подробнее о событии')),
            ],
            options={
                'verbose_name': 'events',
                'verbose_name_plural': 'События',
            },
        ),
    ]
