# Generated by Django 4.2.5 on 2023-10-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Логин')),
                ('title', models.CharField(max_length=15, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='portfolio/image', verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('url', models.URLField(blank=True, verbose_name='В сотрудничестве')),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
