# Generated by Django 4.2.6 on 2023-10-16 11:21

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_artwork_image_alter_artwork_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='thumb',
            field=models.ImageField(upload_to=portfolio.models.thumb_directory_path, verbose_name='Миниатюра'),
        ),
    ]
