# Generated by Django 4.2.5 on 2023-10-05 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=256, verbose_name='Ссылка на фото')),
                ('image', models.ImageField(upload_to='userprofile/image', verbose_name='Изображение')),
                ('firstname', models.CharField(max_length=15, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('e_mail', models.CharField(max_length=15, verbose_name='Почта')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('sotial_vk', models.CharField(max_length=15, verbose_name='Вконтакте')),
                ('sotial_ok', models.CharField(max_length=15, verbose_name='Одноклассники')),
                ('sotial_inst', models.CharField(max_length=15, verbose_name='Инста')),
                ('sotial_tube', models.CharField(max_length=15, verbose_name='Видео')),
                ('username', models.CharField(max_length=15, verbose_name='Логин')),
                ('password', models.CharField(max_length=15, verbose_name='Пароль')),
                ('about', models.TextField(verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'userprofile',
                'verbose_name_plural': 'Профиль',
            },
        ),
    ]
