# Generated by Django 4.2.5 on 2023-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sotial_inst',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sotial_ok',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sotial_tube',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sotial_vk',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_inst',
            field=models.CharField(blank=True, max_length=25, verbose_name='Инста'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_ok',
            field=models.CharField(blank=True, max_length=25, verbose_name='Одноклассники'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_tube',
            field=models.CharField(blank=True, max_length=25, verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_vk',
            field=models.CharField(blank=True, max_length=25, verbose_name='Вконтакте'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='e_mail',
            field=models.CharField(blank=True, max_length=25, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=25, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=25, verbose_name='Логин'),
        ),
    ]
