# Generated by Django 4.2.5 on 2023-10-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='e_mail',
            field=models.CharField(blank=True, max_length=15, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='userprofile/image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=15, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=15, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo_url',
            field=models.CharField(blank=True, max_length=256, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sotial_inst',
            field=models.CharField(blank=True, max_length=15, verbose_name='Инста'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sotial_ok',
            field=models.CharField(blank=True, max_length=15, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sotial_tube',
            field=models.CharField(blank=True, max_length=15, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sotial_vk',
            field=models.CharField(blank=True, max_length=15, verbose_name='Вконтакте'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=15, verbose_name='Логин'),
        ),
    ]
