# Generated by Django 4.2.5 on 2023-10-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginuser', '0002_alter_userprofile_about_alter_userprofile_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(blank=True, verbose_name='Телефон'),
        ),
    ]
